-- ============================================
-- SCRIPT 4: CREATE_VALIDATION_PACKAGE.sql
-- Connect as CRS_ADMIN and run this script
-- ============================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE CRS_VALIDATION_PKG';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE BODY CRS_VALIDATION_PKG';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/